# Generated by Django 6.0.3 on 2026-03-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=4, help_text='Nombre de places', verbose_name='Capacité'),
        ),
        migrations.AddField(
            model_name='table',
            name='color',
            field=models.CharField(default='#3B82F6', help_text='Couleur de la table (format hexadécimal, ex: #FF5733)', max_length=7, verbose_name='Couleur'),
        ),
        migrations.AddField(
            model_name='table',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
