# Generated by Django 6.0.3 on 2026-03-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_table_capacity_table_color_table_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Thème Principal', max_length=50, verbose_name='Nom du thème')),
                ('theme_mode', models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre'), ('auto', 'Automatique')], default='light', max_length=10, verbose_name='Mode du thème')),
                ('primary_color', models.CharField(default='#3B82F6', help_text='Couleur primaire (boutons, liens)', max_length=7, verbose_name='Couleur principale')),
                ('primary_hover', models.CharField(default='#2563EB', max_length=7, verbose_name='Couleur principale (survol)')),
                ('primary_light', models.CharField(default='#DBEAFE', max_length=7, verbose_name='Couleur principale (clair)')),
                ('sidebar_bg', models.CharField(default='#1E293B', help_text='Arrière-plan de la barre latérale', max_length=7, verbose_name='Sidebar (fond)')),
                ('sidebar_bg_gradient', models.CharField(default='#0F172A', help_text='Couleur de fin du dégradé', max_length=7, verbose_name='Sidebar (dégradé)')),
                ('sidebar_text', models.CharField(default='#F8FAFC', max_length=7, verbose_name='Sidebar (texte)')),
                ('bg_color', models.CharField(default='#F9FAFB', max_length=7, verbose_name='Arrière-plan général')),
                ('card_bg', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Cartes (fond)')),
                ('text_primary', models.CharField(default='#1F2937', max_length=7, verbose_name='Texte principal')),
                ('text_secondary', models.CharField(default='#6B7280', max_length=7, verbose_name='Texte secondaire')),
                ('success_color', models.CharField(default='#10B981', max_length=7, verbose_name='Succès (vert)')),
                ('warning_color', models.CharField(default='#F59E0B', max_length=7, verbose_name='Avertissement (orange)')),
                ('danger_color', models.CharField(default='#EF4444', max_length=7, verbose_name='Danger/Erreur (rouge)')),
                ('info_color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Information (bleu)')),
                ('border_color', models.CharField(default='#E5E7EB', max_length=7, verbose_name='Couleur des bordures')),
                ('border_radius', models.PositiveSmallIntegerField(default=8, help_text='Rayon des bords en pixels', verbose_name='Arrondi des bords (px)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Thème Admin',
                'verbose_name_plural': 'Thèmes Admin',
            },
        ),
    ]
