# Generated by Django 6.0.3 on 2026-03-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='QR code pour accéder au menu de la table', null=True, upload_to='qr_tables/', verbose_name='QR Code'),
        ),
    ]
