# Generated by Django 6.0.3 on 2026-03-28 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_table_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='qr_code',
        ),
    ]
