# Generated by Django 6.0.3 on 2026-03-28 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_remove_table_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du restaurant')),
                ('slug', models.SlugField(unique=True, verbose_name='Identifiant URL')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('country', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurants/', verbose_name='Logo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='restaurants/', verbose_name='Bannière')),
                ('primary_color', models.CharField(default='#3B82F6', help_text='Couleur par défaut pour les tables', max_length=7, verbose_name='Couleur principale')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='menu.restaurant', verbose_name='Restaurant'),
        ),
        migrations.AddField(
            model_name='table',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='menu.restaurant', verbose_name='Restaurant'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['restaurant', '-created_at'], name='menu_commen_restaur_01db2c_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['restaurant', 'is_active'], name='menu_table_restaur_e89aca_idx'),
        ),
    ]
