# Generated by Django 6.0.3 on 2026-03-28 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_restaurant_comment_restaurant_table_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='menu.restaurant', verbose_name='Restaurant'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['restaurant', 'order'], name='menu_catego_restaur_1a6940_idx'),
        ),
    ]
