# Generated by Django 6.0.3 on 2026-03-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_category_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_occupied',
            field=models.BooleanField(default=False, verbose_name='Occupée'),
        ),
    ]
