# Generated by Django 6.0.3 on 2026-03-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_table_is_occupied'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='currency',
            field=models.CharField(choices=[('EUR', '€ - Euro'), ('USD', '$ - Dollar US'), ('XAF', 'FCFA - Franc CFA'), ('XOF', 'CFA - Franc Ouest Africain'), ('GBP', '£ - Livre Sterling'), ('CHF', 'CHF - Franc Suisse'), ('CAD', 'C$ - Dollar Canadien')], default='EUR', max_length=3, verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='custom_exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text="Taux par rapport à l'EUR (1 EUR = X devise)", max_digits=10, verbose_name='Taux de conversion personnalisé'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='vat_enabled',
            field=models.BooleanField(default=True, verbose_name='Afficher la TVA'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Taux de TVA en pourcentage', max_digits=5, verbose_name='Taux de TVA (%)'),
        ),
    ]
