# Generated by Django 6.0.3 on 2026-03-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_restaurant_currency_restaurant_custom_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Prix (FCFA)'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='currency',
            field=models.CharField(choices=[('XAF', 'FCFA - Franc CFA'), ('EUR', '€ - Euro'), ('USD', '$ - Dollar US'), ('XOF', 'CFA - Franc Ouest Africain'), ('GBP', '£ - Livre Sterling'), ('CHF', 'CHF - Franc Suisse'), ('CAD', 'C$ - Dollar Canadien')], default='XAF', max_length=3, verbose_name='Devise par défaut'),
        ),
    ]
