# Generated by Django 6.0.3 on 2026-03-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_menuitem_price_alter_restaurant_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='mompay_enabled',
            field=models.BooleanField(default=False, verbose_name='Activer MomPay'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='mompay_merchant_code',
            field=models.CharField(blank=True, help_text='Code marchand pour le paiement MomPay (laisser vide pour désactiver)', max_length=50, verbose_name='Code marchand MomPay'),
        ),
    ]
