# Generated by Django 6.0.3 on 2026-03-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='bill_notification_repeats',
            field=models.PositiveSmallIntegerField(default=1, help_text='Nombre de fois que la notification vocale est répétée (1-5)', verbose_name='Répétitions notification vocale'),
        ),
    ]
