# Generated by Django 6.0.3 on 2026-03-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_add_bill_notification_repeats'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill_requested',
            field=models.BooleanField(default=False, verbose_name='Addition demandée'),
        ),
        migrations.AddField(
            model_name='order',
            name='bill_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date demande addition'),
        ),
    ]
